import { jsx as _jsx } from "react/jsx-runtime";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children, }) {
    return (_jsx("html", { lang: "en", children: _jsx("body", { className: `${inter.className} antialiased`, children: children }) }));
}
